### ISSUE TITLE
constants.service.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [SergeyUdovenko/shop#4]
Не понял зачем объявляется, если не используется. Ведь в методе этот объект переопределяется.
Constants = {
    App: 'Shop',
    Version: '0.1.0',
    Owner: 'Anonymos'
  };

**Comment by SergeyUdovenko** [comment]
Если не обьявлять, линтер ругается

**Comment by VZhyrytskiy** [comment]
У меня не ругается. Может не туда смотрю. Можно картинку?

**Comment by SergeyUdovenko** [comment]
У меня тоже престал ругаться, спасибо)
